import { z } from "zod";

export const scholarshipSchema = z.object({
  universityName: z.string().trim().min(2, "University name 2-120 chars").max(120),
  scholarshipName: z.string().trim().min(2, "Scholarship name 2-200 chars").max(200).optional().or(z.literal("")),
  country: z.string().trim().min(2, "Country required").max(80),
  city: z.string().trim().min(2, "City required").max(80),
  universityWorldrank: z.coerce.number().int().min(1, "Rank 1+").max(10000),
  stipend: z.coerce.number().min(0).optional().or(z.literal("")),
  scholarshipCategory: z.enum(["Partial", "Full-fund", "Self-fund"], { errorMap: () => ({ message: "Select category" }) }),
  subjectName: z.string().trim().min(2, "Subject required").max(80),
  degree: z.enum(["Diploma", "Bachelor", "Masters", "PhD"]),
  currency: z.enum(["USD", "GBP", "EUR"]).default("USD"),
  duration: z.string().trim().max(60).optional().or(z.literal("")),
  eligibility: z.string().trim().max(1000).optional().or(z.literal("")),
  benefits: z.string().trim().max(1000).optional().or(z.literal("")),
  tags: z.string().trim().max(500).optional().or(z.literal("")),
  highlights: z.string().trim().max(500).optional().or(z.literal("")),
  documents: z.string().trim().max(1000).optional().or(z.literal("")),
  requirements: z.string().trim().max(1000).optional().or(z.literal("")),
  scholarshipDescription: z.string().trim().min(20, "Description 20+ chars").max(2000),
  applicationDeadline: z.string().min(1, "Deadline required"),
  galleryUrls: z.string().trim().max(2000).optional().or(z.literal("")),
  videoUrl: z.string().trim().url("Invalid URL").or(z.literal("")).optional(),
  videoPoster: z.string().trim().url("Invalid URL").or(z.literal("")).optional(),
  brochureUrl: z.string().trim().url("Invalid URL").or(z.literal("")).optional(),
  mapUrl: z.string().trim().url("Invalid URL").or(z.literal("")).optional(),
  faqs: z.string().trim().max(3000).optional().or(z.literal("")),
  serviceCharge: z.coerce.number().min(0, "Service charge ≥0").max(10000),
  applicationFees: z.coerce.number().min(0, "Application fee ≥0").max(10000),
});

export const defaultValues = {
  universityName: "",
  scholarshipName: "",
  country: "",
  city: "",
  universityWorldrank: "",
  stipend: "",
  scholarshipCategory: "Partial",
  subjectName: "Agriculture",
  degree: "Diploma",
  currency: "USD",
  duration: "",
  eligibility: "",
  benefits: "",
  tags: "",
  highlights: "",
  documents: "",
  requirements: "",
  scholarshipDescription: "",
  applicationDeadline: "",
  galleryUrls: "",
  videoUrl: "",
  videoPoster: "",
  brochureUrl: "",
  mapUrl: "",
  faqs: "",
  serviceCharge: "",
  applicationFees: "",
};
